version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - graphviz
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - mkdir ~/.casa

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
