version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
    install:
      - uv pip install --upgrade pip
      - uv pip install --group docs .

sphinx:
  configuration: docs/conf.py
