[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "radiotools"
description = "Tools for radio astronomy."
readme = "README.rst"
authors = [
  {name = radionets-project developers}
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Development Status :: 3 - Alpha",
]

dynamic = ["version"]
requires-python = ">=3.10"

dependencies = [
  "astropy >=6.1.0",
  "matplotlib ~=3.0",
  "numpy ~=1.16",
  "pyvisgen",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "setuptools_scm[toml]",
]

[project.urls]
repository = "https://github.com/radionets-project/radiotools"

[tool.setuptools.packages.find]
where = ["radiotools"]

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "I",  # isort
]
ignore = []

fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
known-first-party = [
  "pyvisgen",
  "radiotools",
  "radionets"
]
